# https://alacritty.org/config-alacritty.html

###########
# GENERAL #
###########

# Import additional configuration files
import = []

# Shell program and its arguments
#[shell]
#program = "/bin/zsh"  # Default $SHELL
#args = ["-l"]

# Working directory
working_directory = "None"  # Default: "None"

# Live config reload (changes require restart)
live_config_reload = true  # Default: true

# Offer IPC using alacritty msg (unix only)
ipc_socket = true  # Default: true

#######
# ENV #
#######

[env]
# Environment variables
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

###########
## WINDOW #
###########

[window]

# Window dimensions
dimensions = { columns = 0, lines = 0 }  # Default: columns = 0, lines = 0

# Window startup position
position = "None"  # Default: "None"

# Padding
padding = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Dynamic padding
dynamic_padding = true  # Default: false

# Window decorations
decorations = "Full"  # Default: "Full"

# Opacity
opacity = 0.95  # Default: 1.0

# Blur (macOS/KDE Wayland only)
blur = false  # Default: false

# Startup mode
startup_mode = "Windowed"  # Default: "Windowed"

# Window title
title = "Alacritty"  # Default: "Alacritty"

# Dynamic title
dynamic_title = true  # Default: true

# Window class (Linux/BSD only)
class = { instance = "Alacritty", general = "Alacritty" }  # Default: instance = "Alacritty", general = "Alacritty"

# Decorations theme variant
decorations_theme_variant = "None"  # Default: "None"

# Resize increments
resize_increments = false  # Default: false

# Option as Alt (macOS only)
option_as_alt = "None"  # Default: "None"

#############
# SCROLLING #
#############

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 20000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 5  # Default: 3

########
# FONT #
########

[font]

# Normal font style
normal = { family = "monospace", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 16.5  # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

##########
# COLORS #
##########

[colors]

# Transparent background colors
transparent_background_colors = false  # Default false

# Draw bold text with bright colors
draw_bold_text_with_bright_colors = false  # Default false

# Primary colors
[colors.primary]
foreground = "#d8dee9"  # Default "#d8d8d8"
background = "#2e3440"  # Default "#181818"
dim_foreground = "#a5abb6"  # Default "#828482"
bright_foreground = "None"  # Default "None"

# Cursor colors
[colors.cursor]
text = "#2e3440"    # Default "CellBackground"
cursor = "#d8dee9"  # Default "CellForeground"

# Vi mode cursor colors
[colors.vi_mode_cursor]
text = "#2e3440"    # Default "CellBackground"
cursor = "#d8dee9"  # Default "CellForeground"

# Search colors
[colors.search.matches]
foreground = "CellBackground" # Default "#181818"
background = "#88c0d0" # Default "#ac4242"

[colors.search.focused_match]
foreground = "#434c5e" # Default "#181818"
background = "#d8dee9" # Default "#f4bf75"

# Hint colors
[colors.hints.start]
foreground = "#181818"  # Default "#181818"
background = "#f4bf75"  # Default "#f4bf75"

[colors.hints.end]
foreground = "#181818"  # Default "#181818"
background = "#ac4242"  # Default "#ac4242"

# Line indicator colors
[colors.line_indicator]
foreground = "None"  # Default "None"
background = "None"  # Default "None"

# Footer bar colors
[colors.footer_bar]
foreground = "#181818"  # Default "#181818"
background = "#d8d8d8"  # Default "#d8d8d8"

# Selection colors
[colors.selection]
text = "CellForeground"  # Default "CellBackground"
background = "#4c566a"   # Default "CellForeground"

# Normal colors
[colors.normal]
black = "#3b4252" # Default "#181818"
red = "#bf616a" # Default "#ac4242"
green = "#a3be8c" # Default "#90a959"
yellow = "#ebcb8b" # Default "#f4bf75"
blue = "#81a1c1" # Default "#6a9fb5"
magenta = "#b48ead" # Default "#aa759f"
cyan = "#88c0d0" # Default "#75b5aa"
white = "#e5e9f0" # Default "#d8d8d8"

# Bright colors
[colors.bright]
black = "#4c566a" # Default "#6b6b6b"
red = "#bf616a" # Default "#c55555"
green = "#a3be8c" # Default "#aac474"
yellow = "#ebcb8b" # Default "#feca88"
blue = "#81a1c1" # Default "#82b8c8"
magenta = "#b48ead" # Default "#c28cb8"
cyan = "#8fbcbb" # Default "#93d3c3"
white = "#eceff4" # Default "#f8f8f8"

# Dim colors
[colors.dim]
black = "#373e4d" # Default "#0f0f0f"
red = "#94545d" # Default "#712b2b"
green = "#809575" # Default "#5f6f3a"
yellow = "#b29e75" # Default "#a17e4d"
blue = "#68809a" # Default "#456877"
magenta = "#8c738c" # Default "#704d68"
cyan = "#6d96a5" # Default "#4d7770"
white = "#aeb3bb" # Default "#8e8e8e"

# indexed_colors = [] # Default []

########
# BELL #
########

[bell]

# Visual bell animation effect
animation = "Linear"  # Default: "Linear"

# Duration of the visual bell flash in milliseconds
duration = 0  # Default: 0

# Visual bell animation color
color = "#ffffff"  # Default: "#ffffff"

# Command executed when the bell is rung
command = "None"  # Default: "None"

#############
# SELECTION #
#############

[selection]

# Characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"

# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = false  # Default: false

##########
# CURSOR #
##########

[cursor]

# Cursor style
style = { shape = "Block", blinking = "On" }  # Default: shape = "Block", blinking = "Off"

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = { shape = "Block", blinking = "Off" }  # Default: "None"

# Cursor blinking interval in milliseconds
blink_interval = 500  # Default: 750

# Time after which cursor stops blinking, in seconds
blink_timeout = 0  # Default: 5

# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true

# Thickness of the cursor relative to the cell width
thickness = 0.15  # Default: 0.15

#############
## TERMINAL #
#############

[terminal]

# Controls the OSC 52 behavior for clipboard interactions
osc52 = "OnlyCopy"  # Default: "OnlyCopy"

#########
# MOUSE #
#########

[mouse]

# When true, the cursor is temporarily hidden when typing
hide_when_typing = false  # Default: false

# Mouse bindings (actual bindings need to be defined as per user preference)
# Example: bindings = [{ mouse = "Left", action = "Paste" }]
bindings = []

#########
# HINTS #
#########

[hints]

# Define the keys used for hint labels
alphabet = "jfkdls;ahgurieowpq"  # Default: "jfkdls;ahgurieowpq"

# Enable specific hints
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


############
# KEYBOARD #
############

[keyboard]

# Define keyboard bindings here
bindings = [
    { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" },
    { key = "Q", mods = "None", mode = "Vi", action = "ToggleViMode" },
    { key = "Q", mods = "None", mode = "Vi", action = "ScrollToBottom" },
    { key = "Escape", mods = "Alt", mode = "Vi", action = "ToggleViMode" },
    { key = "Escape", mods = "Alt", mode = "Vi", action = "ScrollToBottom" },
    { key = "Escape", mods = "Alt", action = "ToggleViMode" }

]
